### ISSUE TITLE
How to center an image vertically?

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/basis#18]
I would like to be able on one single-column page to center an image vertically. How best should I do this in Basis?

**Comment by wesruv** [comment]
This isn't necessarily hard, but it'd be a little tricky to give you utility class to do it with. It depends a lot on context.

Let's say our markup is:

``` html
<div class="image-wrapper">
  <img class="vertically-centered-image" src="..." alt="" />
</div>
```

### My favorite way

``` css
.image-wrapper {
  position: relative;
  height: 500px;
}

.vertically-centered-image {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

This works because`top` and `left` are calculating their final value based on the parent's dimensions, and translate uses the child element's dimensions.

I put a height on the image wrapper only because the height will need to be set by something other than the centered image if we use position absolute. Depending on what you're trying to do, `position: relative;` may also be a good/better choice.

Great article on this technique here:
http://zerosixthree.se/vertical-align-anything-with-just-3-lines-of-css/

### Flexbox way

If the parent element is a flex container, or you're comfortable making a wrapper that's a flex container:

``` css
.image-wrapper {
  display: flex;
  /* If every child of this element should be centered vertically you can use: */
  /* align-items: center; */
}

.image {
  align-self: center;
}
```

I've literally learned everything I know about flexbox from this page (and goofing off with it):
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

I type it in my browser so much it's auto-completed any time I type 'css' into my browser bar.

You can also check out this page:
https://css-tricks.com/centering-css-complete-guide/

**Comment by wesruv** [comment]
Made a quick codepen: http://codepen.io/wesruv/pen/GZPvxY

With the transform method you're going to risk the image laying over top of other elements. Whether you use `position: relative` or `position: absolute`.

If you end up using the flexbox method, be aware that by default flexbox does not wrap, it squishes. You can make it allow wrapping by adding this to the parent:

``` css
.image-wrapper {
  flex-wrap: wrap;
}
```
